DROP PROCEDURE SCOTT.DBS_STU_UPDATE;

CREATE OR REPLACE PROCEDURE SCOTT.DBS_STU_UPDATE(p_admno number,p_fee number) IS
BEGIN
   UPDATE DBS_STU 
   SET FEE=FEE-p_fee
   WHERE ADMNO=p_admno;
   COMMIT;
END;
/
